# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160226_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpage',
            name='Photo',
        ),
        migrations.AddField(
            model_name='flatpage',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
