# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160226_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
