# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160229_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='menu',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, upload_to='new'),
        ),
    ]
